<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gpd</name>
  <version>2.0.0</version>
  <description>Detect 6-DOF grasp poses in point clouds</description>
  <maintainer email="Christian.Rauch@unileoben.ac.at">Christian Rauch</maintainer>
  <license>BSD-2-Clause</license>

  <buildtool_depend>cmake</buildtool_depend>

  <build_depend>eigen</build_depend>
  <depend>libopencv-dev</depend>
  <depend>libpcl-all-dev</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
